import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy.stats import pearsonr
import argparse

### This file plots the expression heatmap ###

# input
parser = argparse.ArgumentParser()
parser.add_argument('Input_File' , help="Specify the location of the expression_levels.csv file (generated by get_expression_levels.py)")
args = vars(parser.parse_args())
fname = args['Input_File']

# read in the expression level file
df_expr = pd.read_csv(fname, sep='\t')
h = df_expr[['ENCFF297CNO_TPM',  'ENCFF879WBJ_TPM',  'ENCFF285HUZ_TPM', 'ENCFF853TRI_TPM', 'ENCFF305QBE_TPM']]
h.index = df_expr['# MA']
h = h.T

sns.heatmap(h, cmap='YlGnBu')
plt.show()

hh = h.sort_values(by='ENCFF297CNO_TPM', axis=1, ascending=False)
plt.clf()
sns.heatmap(hh, cmap='YlGnBu')
plt.show()

print (pearsonr(h.iloc[0], h.iloc[1]))
print (pearsonr(h.iloc[0], h.iloc[2]))
print (pearsonr(h.iloc[1], h.iloc[2]))

print (pearsonr(h.iloc[0], h.iloc[3]))
print (pearsonr(h.iloc[0], h.iloc[4]))